# -*- coding: utf-8 -*-
"""intelligent_bandwidth_allocator.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18TFnUvJg4X_mTHIrY2jFsbtRsVJJwTag
"""

import torch
import torch.nn as nn
import torch.nn.functional as F
import matplotlib.pyplot as plt

# Dummy ExternalAttention module (for demonstration)
class ExternalAttention(nn.Module):
    def __init__(self, embed_dim):
        super().__init__()
        self.fc = nn.Linear(embed_dim, embed_dim)
    def forward(self, x):
        # simple attention-like scaling
        attn = torch.sigmoid(self.fc(x))
        return x * attn

# Define your model
class IntelligentBandwidthAllocator(nn.Module):
    def __init__(self, vocab_size=256, embed_dim=64,
                 hidden_dim=128, num_classes=6, dropout=0.3):
        super().__init__()
        self.embedding = nn.Embedding(vocab_size, embed_dim)
        self.embedding_dropout = nn.Dropout(dropout)
        self.attention = ExternalAttention(embed_dim)
        self.conv_layers = nn.ModuleList([
            nn.Conv1d(embed_dim, 128, kernel_size=k, padding=k//2, bias=False)
            for k in [3,5,7]
        ])
        self.conv_bn = nn.ModuleList([nn.BatchNorm1d(128) for _ in range(3)])
        self.bilstm = nn.LSTM(input_size=384, hidden_size=hidden_dim,
                              num_layers=2, bidirectional=True,
                              batch_first=True, dropout=dropout)
        self.classifier = nn.Sequential(
            nn.Linear(hidden_dim*2, 256), nn.ReLU(), nn.BatchNorm1d(256),
            nn.Dropout(dropout),
            nn.Linear(256,128), nn.ReLU(), nn.Dropout(dropout),
            nn.Linear(128,num_classes)
        )

    def forward(self, x):
        embedded = self.embedding_dropout(self.embedding(x))
        attended = self.attention(embedded)
        conv_outputs = []
        for conv, bn in zip(self.conv_layers, self.conv_bn):
            conv_out = F.relu(bn(conv(attended.transpose(1,2))))
            conv_outputs.append(conv_out)
        cnn_features = torch.cat(conv_outputs, dim=1).transpose(1,2)
        lstm_out, _ = self.bilstm(cnn_features)
        final_hidden = lstm_out[:,-1,:]
        logits = self.classifier(final_hidden)
        return F.softmax(logits, dim=1)

# ------------------------------
# Generate some random input data
batch_size = 10
sequence_length = 20
x = torch.randint(0, 256, (batch_size, sequence_length))

# Instantiate the model
model = IntelligentBandwidthAllocator()

# Forward pass
output_probs = model(x)  # shape: [batch_size, num_classes]

# Print output probabilities
print("Predicted probabilities:\n", output_probs)

# ------------------------------
# Visualization: heatmap of predictions
plt.figure(figsize=(8,4))
plt.imshow(output_probs.detach().numpy(), cmap='viridis', aspect='auto')
plt.colorbar(label='Probability')
plt.xlabel('Classes')
plt.ylabel('Samples')
plt.title('Intelligent Bandwidth Allocator Predictions')
plt.show()