# -*- coding: utf-8 -*-
"""Training Simulation pytorch deep learning

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-NaM5mcyoTlq49BpmU-6zsZiZ_uxrxxW
"""



import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset, random_split
import matplotlib.pyplot as plt
import numpy as np

# -------------------------------
# Step 1: Define External Attention
# -------------------------------
class ExternalAttention(nn.Module):
    def __init__(self, embed_dim):
        super().__init__()
        self.fc = nn.Linear(embed_dim, embed_dim)
        self.softmax = nn.Softmax(dim=1)
    def forward(self, x):
        attn_weights = self.softmax(self.fc(x))
        return x * attn_weights

# -------------------------------
# Step 2: Define IntelligentBandwidthAllocator
# -------------------------------
class IntelligentBandwidthAllocator(nn.Module):
    def __init__(self, vocab_size=256, embed_dim=64,
                 hidden_dim=128, num_classes=6, dropout=0.3):
        super().__init__()
        self.embedding = nn.Embedding(vocab_size, embed_dim)
        self.embedding_dropout = nn.Dropout(dropout)
        self.attention = ExternalAttention(embed_dim)
        self.conv_layers = nn.ModuleList([
            nn.Conv1d(embed_dim, 128, k, padding=k//2, bias=False) for k in [3,5,7]
        ])
        self.conv_bn = nn.ModuleList([nn.BatchNorm1d(128) for _ in range(3)])
        self.bilstm = nn.LSTM(input_size=384, hidden_size=hidden_dim, num_layers=2,
                              bidirectional=True, batch_first=True, dropout=dropout)
        self.classifier = nn.Sequential(
            nn.Linear(hidden_dim*2, 256), nn.ReLU(), nn.BatchNorm1d(256),
            nn.Dropout(dropout),
            nn.Linear(256, 128), nn.ReLU(), nn.Dropout(dropout),
            nn.Linear(128, num_classes)
        )
    def forward(self, x):
        embedded = self.embedding_dropout(self.embedding(x))
        attended = self.attention(embedded)
        conv_outs = []
        for conv, bn in zip(self.conv_layers, self.conv_bn):
            conv_outs.append(F.relu(bn(conv(attended.transpose(1,2)))))
        cnn_features = torch.cat(conv_outs, dim=1).transpose(1,2)
        lstm_out, _ = self.bilstm(cnn_features)
        final_hidden = lstm_out[:, -1, :]
        logits = self.classifier(final_hidden)
        return logits

# -------------------------------
# Step 3: Simulate Dataset
# -------------------------------
num_samples = 2000
seq_len = 20
num_classes = 6
X = torch.randint(0, 256, (num_samples, seq_len))  # random header sequences
y = torch.randint(0, num_classes, (num_samples,))   # random labels

dataset = TensorDataset(X, y)
train_size = int(0.8*num_samples)
val_size = num_samples - train_size
train_dataset, val_dataset = random_split(dataset, [train_size, val_size])

train_loader = DataLoader(train_dataset, batch_size=64, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=64)

# -------------------------------
# Step 4: Training Configuration
# -------------------------------
device = 'cuda' if torch.cuda.is_available() else 'cpu'
model = IntelligentBandwidthAllocator(num_classes=num_classes).to(device)

# Class balancing for imbalanced data
class_counts = np.bincount(y.numpy(), minlength=num_classes)
class_weights = 1.0 / (class_counts + 1e-6)
class_weights = class_weights / class_weights.sum() * num_classes
criterion = nn.CrossEntropyLoss(weight=torch.tensor(class_weights,dtype=torch.float).to(device))

optimizer = optim.AdamW(model.parameters(), lr=1e-3, weight_decay=1e-4)
scheduler = optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode='min', factor=0.1, patience=5)

# -------------------------------
# Step 5: Training Loop with Visualization
# -------------------------------
num_epochs = 20
train_losses, val_losses = [], []

for epoch in range(num_epochs):
    model.train()
    running_loss = 0
    for batch_x, batch_y in train_loader:
        batch_x, batch_y = batch_x.to(device), batch_y.to(device)
        optimizer.zero_grad()
        logits = model(batch_x)
        loss = criterion(logits, batch_y)
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
        optimizer.step()
        running_loss += loss.item()
    train_losses.append(running_loss / len(train_loader))

    # Validation
    model.eval()
    val_loss = 0
    correct, total = 0, 0
    with torch.no_grad():
        for val_x, val_y in val_loader:
            val_x, val_y = val_x.to(device), val_y.to(device)
            logits = model(val_x)
            loss = criterion(logits, val_y)
            val_loss += loss.item()
            preds = logits.argmax(dim=1)
            correct += (preds == val_y).sum().item()
            total += val_y.size(0)
    val_losses.append(val_loss / len(val_loader))
    acc = correct / total
    scheduler.step(val_loss / len(val_loader))
    print(f"Epoch {epoch+1}/{num_epochs}, Train Loss: {train_losses[-1]:.4f}, Val Loss: {val_losses[-1]:.4f}, Val Acc: {acc:.3f}")

# -------------------------------
# Step 6: Plot Loss Curves
# -------------------------------
plt.figure(figsize=(8,5))
plt.plot(train_losses, label='Train Loss', marker='o')
plt.plot(val_losses, label='Validation Loss', marker='o')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.title('Training and Validation Loss')
plt.legend()
plt.grid(True)
plt.show()

# -------------------------------
# Step 7: Class Prediction Distribution (Validation Set)
# -------------------------------
model.eval()
all_preds = []
with torch.no_grad():
    for val_x, _ in val_loader:
        val_x = val_x.to(device)
        preds = model(val_x).argmax(dim=1).cpu().numpy()
        all_preds.extend(preds)
plt.figure(figsize=(8,4))
plt.hist(all_preds, bins=np.arange(num_classes+1)-0.5, rwidth=0.8)
plt.xlabel('Class')
plt.ylabel('Number of Predictions')
plt.title('Predicted Class Distribution (Validation Set)')
plt.grid(True)
plt.show()